[project]
name = "halligame"
version = "0.0.0alpha"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "erpy",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src/halligame"]

[tool.uv.sources]
erpy = { path = "vendor/erpy" }
